---
title: "Moreton Bay Research Center - Carbon Storage"
subtitle: "Carbon Sequestration in Seagrass Meadows in Relation to Proximity to Mangrove Forests"
author: "Mariko Bronson"
date: "27-09-2025"
format:
  html:
  toc: true # use this to display a table of contents
execute:
  message: false # use this to make sure messages don't show up
warning: false # use this to make sure warnings don't show up
---

```{r packages-and-data}

#installing packages
library(tidyverse)
library(here)
library(janitor)
library(flextable)
library(readxl)
library(ggplot2)
library(colorspace)
library(dplyr) 
library(plotly) # JS plots!
library(DT) # JS tables!
library(leaflet) # JS maps!
library(leaflet.extras) # leaflet add-ons!
library(lme4)
library(ggplot2)
library(emmeans)
library(performance)
library(rstatix)
library(viridis)
library(hrbrthemes)
library(plotly)

raw_data <- read_csv("data/blue-carbon-r-raw-data-post-combustion-final.csv")

```

```{r clean}

clean_data <- clean_names(raw_data) |> 
mutate(vegetation_type = as_factor(vegetation_type), #convert to factor
        vegetation_type = fct_relevel(vegetation_type,  #reorder
                                        "Unveg",
                                        "Mangrove",
                                        "Seagrass")) |> 
  mutate(site = as_factor(site),
         site = fct_relevel(site, #convert to factor and reorder
                            "Adams",
                            "One Mile",
                            "Myora"),
         sample_id = str_remove(sample_id, "\\*")) |> #remove asterisks
  
   filter(!sample_id %in% c("MU.1.44.5")) |>  #remove extra datapoint 
  
    separate(sample_id, 
           into = c("habitat_code", "site_code", "depth"), 
           sep = "\\.",  # Split on periods
           remove = FALSE) |>   # Keep original sample_id column
  mutate(depth = as.numeric(depth)) |>   # Convert depth to number 
  
  select(habitat_code, site_code, depth, vegetation_type, site, bulk_density_g_cm_3, percent_loi_percent_lost_on_ignition, carbon_in_common_units_mg_c_hectare, distance_to_nearest_mangrove_m, distance_to_nearest_seagrass_m, height_of_sample_cylinder_sample_cm) |> 
  #select columns for table
  
  rename(bulk_density = bulk_density_g_cm_3,
         percent_loi = percent_loi_percent_lost_on_ignition,
         carbon_stock = carbon_in_common_units_mg_c_hectare,
         dist_to_mangroves = distance_to_nearest_mangrove_m,
         dist_to_seagrass = distance_to_nearest_seagrass_m,
         height = height_of_sample_cylinder_sample_cm)   #rename columns
  

#standardize samples in new dataset std_data
std_data = clean_data |> 
  mutate(std_carbon = case_when(
    height != 2 ~ (carbon_stock/(height/2)),
    TRUE ~ carbon_stock
  )) |> 
    select(habitat_code, site_code, depth, vegetation_type, site, std_carbon, height, dist_to_mangroves, dist_to_seagrass) |>  #chose data of interest
  mutate(dist_to_mangroves = as.factor(dist_to_mangroves)) #make mangrove dist a factor

 
```

```{r kruskal}

kruskal.test(std_carbon ~ site, data = std_data)  #chi-squared = 18.84, df = 2, p-value = 8.109e-05


dunn_test(std_data, std_carbon ~ site, p.adjust.method = "bonferroni") |> 
  # adams and one mile signif, adams and myora very signif
  filter(p.adj < 0.05) |>   # Show only significant comparisons
  select(group1, group2, p.adj, p.adj.signif)

summary(std_data)
```

```{r scatterplot by veg}

ggplot(data = std_data) +
  geom_jitter(
       aes(x = dist_to_mangroves,
       y = std_carbon,
       color = vegetation_type),
       width = 0.3,
              height = 0,
              shape = 16, 
              alpha = 0.7,
       size = 2.3) +
  labs( x = "Proximity to Mangroves(m)",
        y = "Standardized Carbon Stock (t/ha)",
        color = "Vegetation Type",
        title = "Effects of proximity of mangrove forests to vegetation on sediment carbon stock") +
  theme_classic() +
  theme(
    panel.border = element_rect(fill = NA),
    axis.text.x = element_text(angle = 0, hjust = 1)
  )+
  scale_colour_manual(values = c("#482277","#287D8E", "#B8DE29"))


```

```{r scatterplot by site}

ggplot(data = std_data) +
  geom_jitter(
       aes(x = dist_to_mangroves,
       y = std_carbon,
       color = site),
       width = 0.3,
              height = 0,
              shape = 16, 
              alpha = 0.7,
       size = 2.3) +
  labs( x = "Proximity to Mangroves(m)",
        y = "Standardized Carbon Stock (t/ha)",
        color = "Site",
        title = "Effects of proximity of mangrove forests to sites on sediment carbon stock") +
  theme_classic() +
  theme(
    panel.border = element_rect(fill = NA),
    axis.text.x = element_text(angle = 0, hjust = 1)
  )+
  scale_colour_manual(values = c("#482277","#287D8E", "#B8DE29"))

```

```{r violin plot}

std_violin <- std_data |> 
  ggplot( aes(x=site, y=std_carbon, fill=site)) + #violin plot by site
    geom_violin() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
    theme_minimal() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    labs(title = "Cumulative sediment carbon stock across sites of interest",
         x = "Site",
         y = "Standardized Carbon Stock (t/ha)")

ggplotly(std_violin)
```

```{r violin of seagrass and unveg only}

no_mangrove_data = std_data |> filter(!vegetation_type %in% c("Mangrove"))
  

no_mangrove_violin <- no_mangrove_data |> 
  ggplot( aes(x=site, y=std_carbon, fill=site)) + #violin plot by site
    geom_violin() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
    theme_minimal() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    labs(title = "Cumulative sediment carbon stock of seagrass and unvegetated areas across sites of interest",
         x = "Site",
         y = "Standardized Carbon Stock (t/ha)")

ggplotly(no_mangrove_violin)

```

```{r scatterplot with no mangroves}

ggplot(data = no_mangrove_data) +
  geom_jitter(
       aes(x = dist_to_mangroves,
       y = std_carbon,
       color = vegetation_type),
       width = 0.3,
              height = 0,
              shape = 16, 
              alpha = 0.7,
       size = 2.3) +
  labs( x = "Proximity to Mangroves(m)",
        y = "Standardized Carbon Stock (t/ha)",
        color = "Vegetation Type",
        title = "Effects of proximity of mangrove forests to vegetation on sediment carbon stock") +
  theme_classic() +
  theme(
    panel.border = element_rect(fill = NA),
    axis.text.x = element_text(angle = 0, hjust = 1)
  )+
  scale_colour_manual(values = c("#482277","#287D8E", "#B8DE29"))


```

```{r kruskal with no mangroves}

kruskal.test(std_carbon ~ site, data = no_mangrove_data)  #chi-squared = 18.84, df = 2, p-value = 8.109e-05


dunn_test(no_mangrove_data, std_carbon ~ site, p.adjust.method = "bonferroni") |> 
  # adams and one mile signif, adams and myora very signif
  filter(p.adj < 0.05) |>   # Show only significant comparisons
  select(group1, group2, p.adj, p.adj.signif)

summary(no_mangrove_data)
```

```{r seagrass kruskal}

seagrass_data <- std_data |> 
  filter(vegetation_type == "Seagrass") 

kruskal.test(std_carbon ~ site, data = seagrass_data)  #chi-squared = 18.84, df = 2, p-value = 8.109e-05


dunn_test(seagrass_data, std_carbon ~ site, p.adjust.method = "bonferroni") |> 
  # adams and one mile signif, adams and myora very signif
  filter(p.adj < 0.05) |>   # Show only significant comparisons
  select(group1, group2, p.adj, p.adj.signif)

summary(seagrass_data)
```

```{r seagrass scatterplot}
ggplot(data = seagrass_data) +
  geom_jitter(
       aes(x = dist_to_mangroves,
       y = std_carbon,
       color = site),
       width = 0.3,
              height = 0,
              shape = 16, 
              alpha = 0.7,
       size = 2.3) +
  labs( x = "Proximity to Mangroves(m)",
        y = "Standardized Carbon Stock (t/ha)",
        color = "Site",
        title = "Effects of proximity of mangrove forests to seagrass on sediment carbon stock") +
  theme_classic() +
  theme(
    panel.border = element_rect(fill = NA),
    axis.text.x = element_text(angle = 0, hjust = 1)
  )+
  scale_colour_manual(values = c("#482277","#287D8E", "#B8DE29"))
```

```{r unveg kruskal}

unveg_data <- std_data |> 
  filter(vegetation_type == "Unveg") 

kruskal.test(std_carbon ~ site, data = unveg_data)  #chi-squared = 18.84, df = 2, p-value = 8.109e-05


dunn_test(unveg_data, std_carbon ~ site, p.adjust.method = "bonferroni") |> 
  # adams and one mile signif, adams and myora very signif
  filter(p.adj < 0.05) |>   # Show only significant comparisons
  select(group1, group2, p.adj, p.adj.signif)

summary(unveg_data)
```

```{r unveg scatterplot}
unveg_scatterplot <- ggplot(data = unveg_data) +
  geom_jitter(
       aes(x = dist_to_mangroves,
       y = std_carbon,
       color = site),
       width = 0.3,
              height = 0,
              shape = 16, 
              alpha = 0.7,
       size = 2.3) +
  labs( x = "Proximity to Mangroves(m)",
        y = "Standardized Carbon Stock (t/ha)",
        color = "Site",
        title = "Effects of proximity of mangrove forests to unvegetated areas on sediment carbon stock") +
  theme_classic() +
  theme(
    panel.border = element_rect(fill = NA),
    axis.text.x = element_text(angle = 0, hjust = 1)
  )+
  scale_colour_manual(values = c("#482277","#287D8E", "#B8DE29")) 

ggplotly(unveg_scatterplot)
```

