---
  title: "Moreton Bay Research Center - Carbon Storage"
subtitle: "Carbon Sequestration in Seagrass Meadows in Relation to Proximity to Mangrove Forests"
author: "Mariko Bronson"
date: "27-09-2025"
format:
  html:
  toc: true # use this to display a table of contents
execute:
  message: false # use this to make sure messages don't show up
warning: false # use this to make sure warnings don't show up
---

```{r packages-and-data}

#installing packages
library(tidyverse)
library(here)
library(janitor)
library(flextable)
library(readxl)
library(ggplot2)
library(colorspace)
library(dplyr) 
library(plotly) # JS plots!
library(DT) # JS tables!
library(leaflet) # JS maps!
library(leaflet.extras) # leaflet add-ons!
library(lme4)
library(ggplot2)
library(emmeans)
library(performance)
library(rstatix)

raw_practice <- read_csv("data/blue-carbon-R-raw-data-post-combustion.csv")

```

```{r clean}

clean_practice <- clean_names(raw_practice) |> 
mutate(vegetation_type = as_factor(vegetation_type), #convert to factor
        vegetation_type = fct_relevel(vegetation_type,  #reorder
                                        "Unveg",
                                        "Mangrove",
                                        "Seagrass")) |> 
  mutate(site = as_factor(site),
         site = fct_relevel(site, #convert to factor and reorder
                            "Adams",
                            "One Mile",
                            "Myora"),
         sample_id = str_remove(sample_id, "\\*")) |> 
  select(sample_id, vegetation_type, site, mangroves, bulk_density_g_cm_3, percent_loi_percent_lost_on_ignition, carbon_stock_t_ha_tons_per_hectare) |> 
  #select columns for table
  rename(bulk_density = bulk_density_g_cm_3,
         percent_loi = percent_loi_percent_lost_on_ignition,
         carbon_stock = carbon_stock_t_ha_tons_per_hectare,
         mangrove_proximity = mangroves)  #rename columns

unfindata <- head(clean_practice, 126) |> 
  filter(!sample_id %in% c("S.2.4", "S.2.10"))

```


```{r initial analyses}

summary(clean_practice)
unfindata |> 
  group_by(vegetation_type, mangrove_proximity) |> 
shapiro_test(carbon_stock)

kruskal.test(carbon_stock ~ interaction(vegetation_type, mangrove_proximity), 
             data = unfindata)


ggplot(unfindata, aes(x = carbon_stock, fill = mangrove_proximity)) +
  geom_density(alpha = 0.6)

anova

```


```{r carbon-stock-scatterplot}

ggplot(data = unfindata) +
  geom_jitter(
       aes(x = mangrove_proximity,
       y = carbon_stock,
       color = vegetation_type),
       width = 0.3,
              height = 0,
              shape = 16, 
              alpha = 0.7,
       size = 2.3) +
  labs( x = "Proximity to Mangroves",
        y = "Carbon Stock (t/ha)",
        color = "Vegetation Type",
        title = "Effects of proximity of mangrove forests to seagrass meadows on sediment carbon stock") +
  theme_classic() +
  theme(
    panel.border = element_rect(fill = NA),
    axis.text.x = element_text(angle = 0, hjust = 1)
  )+
  scale_colour_manual(values = c("#482277","#287D8E", "#B8DE29"))



```

```{r unveg data}

unveg_data <- unfindata |> 
  filter(vegetation_type == "Unveg") |> 
   separate(sample_id, 
           into = c("habitat_code", "site_code", "depth"), 
           sep = "\\.",  # Split on periods
           remove = FALSE) |>   # Keep original sample_id column
  mutate(depth = as.numeric(depth)) |>  # Convert depth to number 
select(habitat_code, depth, mangrove_proximity, carbon_stock)

ggplot(data = unveg_data) +
  geom_jitter(
       aes(x = depth,
       y = carbon_stock,
       color = mangrove_proximity),
       width = 0.3,
              height = 0,
              shape = 16, 
              alpha = 0.7,
       size = 2.3) +
  labs( x = "Depth of Sample (cm)",
        y = "Carbon Stock (t/ha)",
        color = "Proximity to Mangroves",
        title = "Carbon Storage VS Depth of Soil Sample in Unvegetated Areas") +
  theme_classic() +
  theme(
    panel.border = element_rect(fill = NA),
    axis.text.x = element_text(angle = 0, hjust = 1)
  )+
  scale_colour_manual(values = c("#482250","#287D5E", "#B8DE55"))


```

```{r seagrass data}

seagrass_data <- unfindata |> 
  filter(vegetation_type == "Seagrass") |> 
   separate(sample_id, 
           into = c("habitat_code", "site_code", "depth"), 
           sep = "\\.",  # Split on periods
           remove = FALSE) |>   # Keep original sample_id column
  mutate(depth = as.numeric(depth)) |>  # Convert depth to number 
select(habitat_code, depth, mangrove_proximity, carbon_stock)

ggplot(data = seagrass_data) +
  geom_jitter(
       aes(x = depth,
       y = carbon_stock,
       color = mangrove_proximity),
       width = 0.3,
              height = 0,
              shape = 16, 
              alpha = 0.7,
       size = 2.3) +
  labs( x = "Depth of Sample (cm)",
        y = "Carbon Stock (t/ha)",
        color = "Proximity to Mangroves",
        title = "Carbon Storage VS Depth of Soil Sample in Seagrass Areas") +
  theme_classic() +
  theme(
    panel.border = element_rect(fill = NA),
    axis.text.x = element_text(angle = 0, hjust = 1)
  )+
  scale_colour_manual(values = c("#482285","#287D9E", "#B8DE11"))

```


  select(habitat_code, depth, mangrove_proximity, carbon_stock)